spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cherish
    username: postgres
    password: 12345
    show-sql: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    include: smtp

logging:
  level:
    org:
      hibernate:
        sql: debug

jwt:
  secret: akwEyVBsYt9djeG77Tejkeo83yzblYcfPQye08f7MGVdjdo19A


